CREATE DATABASE PRACTICE_5;

use practice_5;

SELECT concat(emp.firstname," ",emp.lastname) as EMPLOYEE_NAME,concat(MNG.firstname," ",MNG.lastname) as MANAGER_NAME 
FROM EMPLOYEES AS EMP JOIN EMPLOYEES AS MNG
ON EMP.REPORTSTO = MNG.EMPLOYEENUMBER;

SELECT EMP.FIRSTNAME AS EMPLOYEE_N , MNG.FIRSTNAME AS MANAGER_N
FROM EMPLOYEES AS EMP CROSS JOIN EMPLOYEES AS MNG;



CREATE TABLE CUSTOMER(
CUST_ID INT PRIMARY KEY,
CUSTOMER_NAME VARCHAR(50) NOT NULL,
ZIPCODE CHAR(6)
);

SELECT * FROM CUSTOMER;

INSERT INTO CUSTOMER VALUES (1,"Rishu","123456");

INSERT INTO CUSTOMER VALUES 
(2,"ABC","151231"),
(3,"XYZ","241211"),
(4,"ROHINI","748955"),
(5,"MITHILESH","131311");

INSERT INTO CUSTOMER(CUSTOMER_NAME,CUST_ID,ZIPCODE) VALUES ("Naynish",6,"135132");

ALTER TABLE CUSTOMER ADD PHONE_NUMBER INT;

ALTER TABLE CUSTOMER MODIFY PHONE_NUMBER VARCHAR(10);

ALTER TABLE CUSTOMER RENAME COLUMN CUSTOMER_NAME TO FIRST_NAME;

ALTER TABLE CUSTOMER RENAME TO CUSTOMER_DETAILS;

SELECT * FROM CUSTOMER_DETAILS;

UPDATE CUSTOMER_DETAILS SET PHONE_NUMBER = "65876212" WHERE CUST_ID = 1;

UPDATE CUSTOMER_DETAILS SET PHONE_NUMBER = "46121211" WHERE CUST_ID IN (3,5,6);

UPDATE CUSTOMER_DETAILS SET FIRST_NAME = "VEDA" WHERE CUST_ID = 2;

UPDATE CUSTOMER_DETAILS SET PHONE_NUMBER = "65876212" WHERE CUST_ID >= 1;

DELETE FROM CUSTOMER_DETAILS WHERE CUST_ID = 3;

-- DELETE FROM CUSTOMER_DETAILS WHERE FIRST_NAME = "ROHINI";

TRUNCATE CUSTOMER_DETAILS;

DROP TABLE CUSTOMER_DETAILS;

DROP DATABASE PRACTICE_5;