CREATE DATABASE farmer_market_5;
USE farmer_market_5;

CREATE TABLE CUSTOMER(
CU_ID INT PRIMARY KEY,
CUSTOMER_NAME VARCHAR(50) NOT NULL,
ZIPCODE CHAR(6)
);

SELECT * FROM CUSTOMER;

INSERT INTO CUSTOMER VALUES (1,"NAYNISH","895626");

INSERT INTO CUSTOMER VALUES 
(2,"RAJ","412311"),
(3,"TEJAS","131212"),
(4,"APEKSHA","565656");

INSERT INTO CUSTOMER(CUSTOMER_NAME,CU_ID,ZIPCODE) VALUES ("LADKAT",5,"895626");

ALTER TABLE CUSTOMER ADD PHONE_NUMBER INT;

ALTER TABLE CUSTOMER MODIFY PHONE_NUMBER VARCHAR(10);

ALTER TABLE CUSTOMER RENAME COLUMN CUSTOMER_NAME TO FIRST_NAME;

ALTER TABLE CUSTOMER RENAME TO CUSTOMER_DETAILS;

SELECT * FROM CUSTOMER_DETAILS;

UPDATE CUSTOMER_DETAILS SET CUSTOMER_NAME = "PREETI" WHERE CU_ID = 5;

UPDATE CUSTOMER_DETAILS SET CUSTOMER_NAME = "NEHA" WHERE CU_ID = 2;

-- INSERT INTO CUSTOMER_DETAILS(PHONE_NUMBER) VALUES ("5152151");

UPDATE CUSTOMER_DETAILS SET PHONE_NUMBER = "44556565" WHERE CU_ID > 0;

DELETE FROM CUSTOMER_DETAILS WHERE CU_ID = 2;

TRUNCATE CUSTOMER_DETAILS;

DROP TABLE CUSTOMER_DETAILS;

DROP DATABASE FARMER_MARKET_5;