CREATE DATABASE FARMER_MARKET;

USE FARMER_MARKET;

CREATE TABLE CUSTOMER(
CU_ID INT PRIMARY KEY,
CUSTOMER_NAME VARCHAR(50) NOT NULL,
ZIPCODE CHAR(6)
);

SELECT * FROM CUSTOMER;

INSERT INTO CUSTOMER VALUES (1,"JASON",111021);

INSERT INTO CUSTOMER VALUES
(2,"SCHOOL",111021);

INSERT INTO CUSTOMER (CUSTOMER_NAME,CU_ID,ZIPCODE) VALUES
("RAJ",3,111021),
("TEJAS",4,111021);

ALTER TABLE CUSTOMER ADD PHONE_NUMBER INT;

ALTER TABLE CUSTOMER MODIFY PHONE_NUMBER VARCHAR(12);

ALTER TABLE CUSTOMER RENAME COLUMN CUSTOMER_NAME TO FIRST_NAME;

ALTER TABLE CUSTOMER RENAME TO CUSTOMER_DETAILS;

SELECT * FROM CUSTOMER_DETAILS;

UPDATE CUSTOMER_DETAILS SET FIRST_NAME = "NEHA" WHERE CU_ID = 2;

UPDATE CUSTOMER_DETAILS SET PHONE_NUMBER = "7777777" WHERE CU_ID >0;

UPDATE CUSTOMER_DETAILS SET FIRST_NAME = "PREETI",ZIPCODE=111312 WHERE CU_ID = 2;

DELETE FROM CUSTOMER_DETAILS WHERE CU_ID = 2;

TRUNCATE CUSTOMER_DETAILS;

DROP TABLE CUSTOMER_DETAILS;

DROP DATABASE FARMER_MARKET;